[package]
name = "lamport_signature"
version = "0.1.0"
authors = ["Henrique Sasaki Yuya <moriturus@alimensir.com>"]

[dependencies]
rand = "0.5.0"
digest = "0.7.2"
typenum = "1.10.0"

[dev-dependencies]
sha2 = "0.7.1"
sha3 = "0.7.3"
groestl = "0.7.0"
blake2 = "0.7.1"
whirlpool = "0.7.1"

